server:
  port: 1000

spring:
  # Active reading config from local file system
  profiles:
    active: native

  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          #searchLocations: file:///D:/Repository/github/spring-cloud-poc/config-server/configs
          searchLocations: /usr/edi/spring/configs
   #     git:
          # uri: https://github.com/sunnykaka/mysteam-config-repo
   #       uri: file:///D:/Repository/github/spring-cloud-poc/config-server/configs
    #      basedir: target/config
   #       searchPaths: "*"

management:
  context-path: /admin

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
